syn_model_dir: voicecloning/synthesizer/saved_models/logs-pretrained/
voc_model_fpath: voicecloning/vocoder/saved_models/pretrained/pretrained.pt
enc_model_fpath: voicecloning/encoder/saved_models/pretrained.pt